apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: qryn
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 9000  # Native protocol port
        - containerPort: 8123  # HTTP interface port
        - containerPort: 9009  # Interserver port
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
