apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: qryn
  labels:
    app: clickhouse
spec:
  ports:
  - name: native
    port: 9000
    targetPort: 9000
  - name: http
    port: 8123
    targetPort: 8123
  - name: interserver
    port: 9009
    targetPort: 9009
  selector:
    app: clickhouse
  type: ClusterIP
