
env:
  CLICKHOUSE_SERVER: "clickhouse.qryn"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DB: "qryn"
  # CLICKHOUSE_AUTH: "default:"
  # CLICKHOUSE_PROTO: "http"
  # CLICKHOUSE_TIMEFIELD: "record_datetime"
  # CLUSTER_NAME: ""
  # BULK_MAXAGE: "2000"
  # BULK_MAXSIZE: "5000"
  # BULK_MAXCACHE: "50000"
  # LABELS_DAYS: "7"
  # SAMPLES_DAYS: "7"
  # HOST: "0.0.0.0"
  # PORT: "3100"
  # QRYN_LOGIN: ""
  # QRYN_PASSWORD: ""
  # READONLY: "false"
  # OMIT_CREATE_TABLES: "false"
  # FASTIFY_BODYLIMIT: "5242880"
  # FASTIFY_REQUESTTIMEOUT: "0"
  # FASTIFY_MAXREQUESTS: "0"
  # FASTIFY_METRICS: "false"
  # ADVANCED_PROMETHEUS_MAX_SAMPLES: "5000000"
  # CORS_ALLOW_ORIGIN: 	"*"
  # TEMPO_SPAN: "24"
  # TEMPO_TAGTRACE: "false"
  # DEBUG: "false"
  # LOG_LEVEL: "info"
  # HASH: "xxhash64"
  # ALERTMAN_URL: "false"
  # ADVANCED_SAMPLES_ORDERING: "timestamp_ns"